import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const patternSvg = `<svg width="20" height="20" xmlns="http://www.w3.org/2000/svg"><circle cx="10" cy="10" r="1.5" fill="gray"/></svg>`;
  const encodedSvg = `data:image/svg+xml;base64,${btoa(patternSvg)}`;
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          className="min-h-screen flex items-center justify-center bg-green-100"
          style={{
            backgroundImage: `url(${encodedSvg})`,
          }}
        >
          {children}
        </div>
      </body>
    </html>
  );
}
